export type { Comment } from './comment'
export type { Dates } from './date'
export type { DetailResponse } from './detail-movie'
export type { Logo } from './image.info'
export type { MovieInfo } from './movie-info'
export type { ResponseData } from './response-data'
export type { Videos } from './video-info'
