export { getImageUrl } from './getImageUrl'
export { getMovieGenre } from './getMovieGenre'
export { getNowPlay } from './getNowPlay'
export { getPopular } from './getPopular'
export { getTopRated } from './getTopRated'
export { getUpComing } from './getUpComing'
