export { DetailPage } from './DetailPage'
export { LandingPage } from './LandingPage'
export { ListPage } from './listPage'
export { MainPage } from './MainPage'
export { NotFoundPage } from './NotFoundPage'
export { SearchPage } from './SearchPage'
