export { DetailPage } from './DetailPage'
export { InfinityListPage } from './InfinityListPage'
export { LandingPage } from './LandingPage'
export { MainPage } from './MainPage'
export { NotFoundPage } from './NotFound'
export { ProfilePage } from './ProfilePage'
export { SearchPage } from './SearchPage'
