export { FamousBody } from './FamousBody'
export { LikeBody } from './LikeBody'
export {ProfileBody} from './ProfileBody'
export { ProfileNavBar } from './ProfileNavBar'
export { ReviewBody } from './ReviewBody'
